### ISSUE TITLE
Categorical Features in initial reference implementation

### ISSUE THREAD

**Issue by fountaindive** [sattarov/FinDiff#1]
Hi, this looks really cool and thanks for adding an implementation online.

I'm playing around with the google colab example you have [here](https://colab.research.google.com/github/sattarov/FinDiff/blob/master/main.ipynb) (linked from the README) and I've found that the categorical columns are not modelled very well whereas the numerical columns are modelled very well. e.g. if you compare 1D histograms for each feature from the training data and the synthetic data.

Do you have any hints to improve the performance for categorical features?

Thanks!

**Comment by sattarov** [comment]
Hi,

Thank you for mentioning that and sorry for the late reply. The reason is that in the educational colab notebook the initial training was set to only 30 epochs. If you increase it by at least 500 you will already notice the improvement. I have updated the notebook correspondingly and also added the automatic switching to GPU to run the training faster. Feel free to check it and let us know if you encounter any issues.

Best regards,
Timur

**Comment by fountaindive** [comment]
Ah ok thanks for getting back to me! I'll give it a go

**Comment by sattarov** [comment]
Hi,

I hope it helped. I close the issue due to inactivity. Feel free to reopen it if you encounter problems.

Best regards,
Timur
